# Generated by Django 4.1.5 on 2023-03-25 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='name', to='articles.article')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='name', to='articles.object')),
            ],
        ),
        migrations.AddField(
            model_name='object',
            name='article',
            field=models.ManyToManyField(related_name='object', through='articles.Relationship', to='articles.article'),
        ),
    ]
